apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  - image: almalinux:9
    name: almalinux
    command: ["sleep", "1000"]
    volumeMounts:
    - mountPath: /mnt/nginx-logs
      name: nginx-logs
      readOnly: true
  volumes:
  - name: nginx-logs
    # this creates intially empty directory in the node where pod scheduled
    emptyDir:
      sizeLimit: 500Mi