apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
  annotations:
    imageregistry: "https://hub.docker.com"
    jenkins-build-url: "https://jenkins.joindeveops.com/build/roboshop/job/2"
spec:
  containers:
  - name: nginx
    image: nginx
